// Register only this requested mother as pending review; merge current state.
const fs=require('fs'),path=require('path');
const dir=__dirname,root=path.resolve(dir,'../../../../../..');
const local=n=>path.join(dir,n),read=p=>JSON.parse(fs.readFileSync(p));
const relative=p=>path.relative(root,p).split(path.sep).join('/');
const qa=read(local('qa-verification.json')),production=read(local('production.json'));
if(Object.values(qa.checks).some(Boolean)||qa.faceSwitching.length!==7)throw new Error('Verification has not passed');
const inspected=['qa-native-layers-light-dark.png','qa-light-dark-scales.png','qa-assembly-detail-dark.png'];
for(const filename of inspected)if(!fs.existsSync(local(filename)))throw new Error('Missing inspection image');
production.checks={...production.checks,outsideRGBA:'passed',outsideRGBAMismatches:0,faceRegion:'passed',faceRegionRGBAMismatches:0,headRGBA:'passed',protectedOpaqueHairRGBA:'passed',originalFaceFiles:'7/7 source SHA-256 verified',faceSwitching:'7/7 fixed-offset pixel checks passed',seams:'inspected',review:'pending',application:'not-integrated'};
production.assembly.hairRanges=[[0,186,66,385],[160,186,242,302]];
production.visualInspection={images:inspected,nativeCanvas:[310,606],displayHeights:[240,256,480],backgrounds:['light','dark'],notes:'Inspected the original head/face fit, hair occlusion by hands and sleeves, cup/saucer, old-arm removal and local skirt edge. User approval is still pending.'};
production.verification='qa-verification.json';
fs.writeFileSync(local('production.json'),JSON.stringify(production,null,2)+'\n');
qa.visualInspection='inspected';qa.visualInspectionImages=inspected;
fs.writeFileSync(local('qa-verification.json'),JSON.stringify(qa,null,2)+'\n');
const statePath=path.join(root,'ArtSources/CharacterExpansion/native-tea/progress.json'),state=read(statePath);
const record=state.outfits['b_'],mother=relative(local('mother-body.png'));
if(record.mother.full&&record.mother.full!==mother)throw new Error('Refusing to replace an existing mother');
record.mother.full=mother;
record.evidence={...record.evidence,full:relative(local('production.json'))};
record.localParts={...record.localParts,full:relative(local('torso-part-native.png'))};
record.checks={...record.checks,full:{nativeCanvas:'passed',alpha:'passed',outsideRGBA:'passed',faceRegion:'passed',headRGBA:'passed',protectedOpaqueHairRGBA:'passed',faceSwitching:'passed',seams:'inspected',review:'pending',application:'not-integrated'}};
record.pixelCheck=['full','close'].every(view=>record.checks[view]?.outsideRGBA==='passed'&&record.checks[view]?.faceRegion==='passed')?'passed':'pending';
state.next={outfit:'b_',view:'full',stage:'review'};
fs.writeFileSync(statePath,JSON.stringify(state,null,2)+'\n');
console.log(JSON.stringify({registeredMother:mother,status:'pending-review',compositeExports:record.composites.full.length,next:state.next},null,2));
