import assert from 'node:assert/strict';
import { _electron as electron } from 'playwright-core';
import { mkdtempSync, writeFileSync, rmSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import path from 'node:path';
import { tmpdir } from 'node:os';
import { desktopMenu } from '../app/shared/menu.ts';
const data=mkdtempSync(path.join(tmpdir(),'chihaya-69-'));
const domain='local.ChihayaPet.QA.'+path.basename(data).replace(/[^a-zA-Z\d]/g,'');
writeFileSync(path.join(data,'config.json'),JSON.stringify({baseURL:'https://example.com/v1',model:'fixture',apiKeys:{'https://example.com/v1':'synthetic'}}));
for(const key of ['idle.enabled','music.autoplayEnabled']) execFileSync('defaults',['write',domain,key,'-bool','false']);
let app;
try {
 app=await electron.launch({args:process.env.CHIHAYA_QA_EXECUTABLE?[]:[path.resolve('.')],executablePath:process.env.CHIHAYA_QA_EXECUTABLE,env:{...process.env,CHIHAYA_QA:'1',CHIHAYA_QA_DATA:data,CHIHAYA_QA_REPLY:'1'}});
 const pet=await app.firstWindow();
 await pet.waitForFunction(()=>window.chihaya?.snapshot().then(s=>!!s.sprite));
 const act=async(action)=>pet.evaluate(a=>window.chihaya.act(a),action);
 const bounds=()=>app.evaluate(({BrowserWindow})=>Object.fromEntries(BrowserWindow.getAllWindows().map(w=>[new URL(w.webContents.getURL()).searchParams.get('window'),{...w.getBounds(),visible:w.isVisible()}])));
 await act({type:'chat'});
 const chat=app.windows().find(p=>p.url().includes('window=chat')) ?? await app.waitForEvent('window');
 await chat.waitForSelector('#input');
 const before=await bounds();
 await app.evaluate(({screen})=>{screen.getCursorScreenPoint=()=>({x:900,y:600});});
 await act({type:'drag',phase:'start'});
 await app.evaluate(({screen})=>{screen.getCursorScreenPoint=()=>({x:300,y:250});});
 await act({type:'drag',phase:'move'}); await act({type:'drag',phase:'end'});
 await act({type:'desktop',field:'height',value:320});
 const after=await bounds();
 console.log('CHAT_FOLLOW',JSON.stringify({before:before.chat,after:after.chat,pet:after.pet,failed:before.chat.x===after.chat.x&&before.chat.y===after.chat.y}));
 await chat.evaluate(()=>window.chihaya.act({type:'input',text:'取消复现'}));
 await chat.evaluate(()=>{void window.chihaya.act({type:'send'});});
 await chat.waitForFunction(()=>window.chihaya.snapshot().then(s=>s.busy==='chat'));
 await chat.evaluate(()=>window.chihaya.act({type:'cancel'}));
 await chat.waitForFunction(()=>window.chihaya.snapshot().then(s=>!s.busy));
 await chat.waitForFunction(()=>document.body.textContent.includes('嗯，那就先停在这里。'));
 await chat.evaluate(()=>window.chihaya.act({type:'close',window:'chat'}));
 const state=await pet.evaluate(()=>window.chihaya.snapshot());
 assert.equal(state.cancelled,true); assert.equal(state.error,undefined);
 console.log('CANCEL_STATE',JSON.stringify({pending:state.pending,error:state.error,menu:desktopMenu(state).find(x=>x.label==='说一句')}));
 await act({type:'say'});
 await pet.waitForFunction(()=>window.chihaya.snapshot().then(s=>s.bubble?.kind==='idle'));
 await new Promise(r=>setTimeout(r,600));
 const cancelled=await bounds();
 console.log('SAY_AFTER_CANCEL',JSON.stringify(cancelled));

 await act({type:'chat'});
 await chat.evaluate(()=>window.chihaya.act({type:'clear'}));
 await chat.evaluate(()=>window.chihaya.act({type:'close',window:'chat'}));
 await act({type:'say'});
 await new Promise(r=>setTimeout(r,600));
 console.log('SAY_AFTER_CLEAR',JSON.stringify(await bounds()));
 const bubbleBefore=await bounds();
 await act({type:'drag',phase:'start'});
 await app.evaluate(({screen})=>{screen.getCursorScreenPoint=()=>({x:600,y:400});});
 await act({type:'drag',phase:'move'}); await act({type:'drag',phase:'end'});
 await act({type:'desktop',field:'height',value:333});
 const moved=await bounds();
 console.log('BUBBLE_FOLLOW',JSON.stringify({before:bubbleBefore.bubble,after:moved.bubble,pet:moved.pet}));
 assert.ok(after.chat.x!==before.chat.x || after.chat.y!==before.chat.y, 'Chat must follow pet');
 assert.ok(cancelled.bubble?.visible, 'Enabled say must produce a visible bubble after cancellation');
 assert.ok(moved.bubble.x!==bubbleBefore.bubble.x || moved.bubble.y!==bubbleBefore.bubble.y, 'Bubble must follow pet');
 console.log('Issue 69 verified: actual window dragging, cancelled chat idle visibility and warm cancellation feedback.');
} finally {await app?.close();execFileSync('defaults',['delete',domain]);rmSync(data,{recursive:true,force:true});}
